# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyoung Min Kim
title: Android Developer
email: rlaudals2374@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kyoungmin-kim-7635189a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: medium
  icon: fas fa-globe
  url: https://rlaudals2374.medium.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a passionate and experienced developer with a focus on the Android platform. Throughout my career, I have been actively involved in the development of numerous Android applications, honing my skills and gaining hands-on experience in the process.

  Furthermore, my dedication to mastering the Android platform led me to dive into the field of Android security during my master's course. This additional study has equipped me with a comprehensive understanding of the security aspects specific to Android platform and Android Application.

  With my expertise in Android development and knowledge of Android security, I am well-equipped to tackle complex projects and ensure the development of secure and robust Android applications. I am eager to apply my skills and contribute to the success of future projects.
  - Java, Kotlin, C++(JNI), Gradle(Groovy), Python, Bash shell
  - Studied AOSP, Android Security
  - CI/CD(Jenkins, Github Actions)
  - Memory analysis in Android native environment

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Naver
        link: https://play.google.com/store/apps/details?id=com.nhn.android.nmap
        sub_title: Android Sdk Engineer
        caption: Dec 2021 - Present
        quote: >
          " Korea No.1 Maps Application "
          
        description: |
          Projects
            - Refactored every codes(code improvment also)
            - Modularization
            - CI/CD for Sdk
            - Memory profiling(Native, Java)
      - layout: left
        title: LINE
        link: https://play.google.com/store/apps/details?id=jp.naver.line.android
        sub_title: Android Sdk Engineer
        caption: Jan 2018 - Nov 2021
        quote: >
          " Google Play Store Downloads 500M Global Messenger "
        description: |
          Projects
            - [Co-viewing in LINE Group Call](https://linecorp.com/en/pr/news/en/2020/3250)
            - [FacePlay based on VoIP 1:1 call](https://linecorp.com/en/pr/news/en/2018/2154)
            - [OA(Official Account) Call - Call using both PSTN and VoIP](https://lineforbusiness.com/th-en/service/oa-call)
            - Refactored VoIP Service code(1:1 call, Group call)
            - Created demo application and documents for LINE VoIP SDK
            - Memory profiling(Native, Java)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Soongsil University
        caption: 2016 - 2018
        sub_title: MS Computer Science (Android Platform Security, Operating System)
        quote: >
        description: |
          Paper
          - [Whitelist for analyzing android malware](https://dl.acm.org/doi/abs/10.1145/3129676.3129726)
          - [Comparative Analysis of Mobile App Reverse Engineering Methods on Dalvik and ART](https://www.semanticscholar.org/paper/Comparative-Analysis-of-Mobile-App-Reverse-Methods-Na-Lim/d67fabdd7e65c2551c2c86f201a67c7f7a143373?p2df)


      - layout: left
        title: Soongsil University
        caption: 2012 - 2016
        sub_title: BS Computer Science
        description: |
          Paper
          - [Design and Implementation of IoT Digital Door Lock System based on Video Communications](https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE06602783)

          Part-time job in DIY Game
          - [KBX(Korea Beer Exchange) Local bar: showing menu/ordering application](https://www.instagram.com/kbx_beer)
          - [Lotte Hotel: Design renewal for Lotte Hotel room management](images/profile.jpg)
          - Broad pharm: Pharmacy application
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Workout
      - Free-diving
      - Take photos

      Look at this cool image  
      ![Trees](images/profile.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
