# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyoung Min Kim
title: Android Developer
email: rlaudals2374@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kyoungmin-kim-7635189a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: medium
  icon: fas fa-globe
  url: https://rlaudals2374.medium.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me

# I am a passionate and experienced developer with a focus on the Android platform. Throughout my career, I have been actively involved in the development of numerous Android applications, honing my skills and gaining hands-on experience in the process.

# Furthermore, my dedication to mastering the Android platform led me to dive into the field of Android security during my master's course. This additional study has equipped me with a comprehensive understanding of the security aspects specific to Android platform and Android Application.

# With my expertise in Android development and knowledge of Android security, I am well-equipped to tackle complex projects and ensure the development of secure and robust Android applications. I am eager to apply my skills and contribute to the success of future projects.
# - Kotlin, Java, C++(JNI), Gradle(Groovy), Python, Bash shell and little bit of Chrome Extensions.
# - Studied AOSP, Android Platform Security in Master degree
# - CI/CD(Jenkins, Github Actions)
# - Memory analysis in Android environment(Java/Native)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a passionate and experienced developer with a strong focus on the Android platform. Throughout my career, I have actively participated in the development of numerous Android applications, refining my skills and gaining valuable hands-on experience in the process.

  Furthermore, my dedication to mastering the Android platform led me to delve into the field of Android security during my master’s course. This additional study has provided me with a comprehensive understanding of the security aspects specific to the Android platform and Android applications.

  With my expertise in Android development and my knowledge of Android security, I am well-equipped to tackle complex projects and ensure the creation of secure and robust Android applications. I am eager to apply my skills and contribute to the success of future projects.

  In terms of technical skills:

  - Languages: Kotlin, Java, C++(JNI), Python, Bash shell, and I also have some experience with Chrome Extensions.
  - Academic Focus: I studied AOSP (Android Open Source Project) and Android Platform Security during my Master's degree.
  - DevOps: Proficient in CI/CD using tools like Jenkins and Github Actions.
  - Technical Analysis: Skilled in memory analysis within the Android environment (both Java and Native).

  

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Naver
        link: https://play.google.com/store/apps/details?id=com.nhn.android.nmap
        sub_title: Android Sdk Engineer
        caption: Dec 2021 - Present
        quote: >
          " Korea No.1 Maps Application "
          
        description: |
          Projects
            - Refactored and optimized codebase for improved performance and maintainability.
            - Implemented modularization for streamlined code organization.
            - Established CI/CD processes, automating key development tasks.
            - Conducted memory profiling for native and Java components to optimize resource usage.

      - layout: left
        title: LINE
        link: https://play.google.com/store/apps/details?id=jp.naver.line.android
        sub_title: Android Sdk Engineer
        caption: Jan 2018 - Nov 2021
        quote: >
          " Google Play Store Downloads 500M Global Messenger "
        description: |
          Projects
            - [Contributed to co-viewing in LINE Group Call](https://linecorp.com/en/pr/news/en/2020/3250)
            - [Contributed to FacePlay for 1:1 calls](https://linecorp.com/en/pr/news/en/2018/2154)
            - [Developed OA Call, integrating PSTN and VoIP call](https://lineforbusiness.com/th-en/service/oa-call)
            - Refactored for VoIP service code, enhancing robustness.
            - Created demo applications and documentation for LINE VoIP SDK.
            - Implemented CI/CD processes and automation for the SDK.
            - Conducted memory profiling to improve overall performance.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Soongsil University
        caption: 2016 - 2018, Seoul, Korea
        sub_title: MS Computer Science (Android Platform Security, Operating System)
        quote: >
        description: |
          Paper
            - [Whitelist for analyzing android malware](https://dl.acm.org/doi/abs/10.1145/3129676.3129726)
            - [Comparative Analysis of Mobile App Reverse Engineering Methods on Dalvik and ART](https://www.semanticscholar.org/paper/Comparative-Analysis-of-Mobile-App-Reverse-Methods-Na-Lim/d67fabdd7e65c2551c2c86f201a67c7f7a143373?p2df)

          Projects
            - [Android Applicaiton code's WhiteList](images/android_whitelist.jpg)
            - [Extract the original code of Andorid App's packed code](images/android_packing_code.jpg)
            - [Studied and analyzed the behavior of Android ART(Based on Android KitKat 4.4)](images/android_art.jpg)
            - [SSUOS: Lab-made tiny OS based on Bochs emulator](images/ssuos.jpg)


      - layout: left
        title: Soongsil University
        caption: 2012 - 2016, Seoul, Korea
        sub_title: BS Computer Science
        description: |
          Paper
          - [Design and Implementation of IoT Digital Door Lock System based on Video Communications](https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE06602783)

          Part-time job in DIY Game
          - [KBX(Korea Beer Exchange) Local bar: showing menu/ordering application](https://www.instagram.com/kbx_beer)
          - [Lotte Hotel: Design renewal for Lotte Hotel room management](images/lotte_hotel2.jpg)
          - [Broad pharm: Pharmacy application](images/broad_pharm2.jpg)
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Workout
      - Free-diving
      - Take photos

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
